version: '3'

services:
  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'
      - './data:/var/lib/neo4j/import'

  web:
    build: '.'
    depends_on:
      - 'db'
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
      - DB_URI=bolt://db:7687
      - DATA_FILE=/data/skills_de.csv
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - './data:/data'
    links:
      - 'db:db'

volumes:
  db:
