version: '3'

services:
  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'

  web:
    build: '.'
    depends_on:
      - 'db'
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - 'db:db'

volumes:
  db:
